DROP MATERIALIZED VIEW GKDW.LAB_COURSE_SCHED_MV_QA;
CREATE MATERIALIZED VIEW GKDW.LAB_COURSE_SCHED_MV_QA 
TABLESPACE GDWLRG
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 29/01/2021 12:20:43 (QP5 v5.115.810.9015) */
SELECT   * FROM "lab_course_sched_v"@rms_dev;

COMMENT ON MATERIALIZED VIEW GKDW.LAB_COURSE_SCHED_MV_QA IS 'snapshot table for snapshot GKDW.LAB_COURSE_SCHED_MV_QA';

GRANT SELECT ON GKDW.LAB_COURSE_SCHED_MV_QA TO DWHREAD;

