DROP MATERIALIZED VIEW GKDW.GK_SOFTLAYER_INSTRUCTORS_MV;
CREATE MATERIALIZED VIEW GKDW.GK_SOFTLAYER_INSTRUCTORS_MV 
TABLESPACE GDWSML
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 29/01/2021 12:22:01 (QP5 v5.115.810.9015) */
SELECT   * FROM gk_softlayer_instructors_v@rms_prod;

COMMENT ON MATERIALIZED VIEW GKDW.GK_SOFTLAYER_INSTRUCTORS_MV IS 'snapshot table for snapshot GKDW.GK_SOFTLAYER_INSTRUCTORS_MV';

GRANT SELECT ON GKDW.GK_SOFTLAYER_INSTRUCTORS_MV TO DWHREAD;

