DROP MATERIALIZED VIEW GKDW.GK_ORACLE_ACCT_NUM_MV;
CREATE MATERIALIZED VIEW GKDW.GK_ORACLE_ACCT_NUM_MV 
TABLESPACE GDWSML
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 29/01/2021 12:23:44 (QP5 v5.115.810.9015) */
SELECT                                                  /*+ DRIVING_SITE(a) */
      ROW_NUMBER () OVER (ORDER BY a.acct_id) P_ID,
         a.*
  FROM   gk_ora_acct_num_v@r12prd a;

COMMENT ON MATERIALIZED VIEW GKDW.GK_ORACLE_ACCT_NUM_MV IS 'snapshot table for snapshot GKDW.GK_ORACLE_ACCT_NUM_MV';

GRANT SELECT ON GKDW.GK_ORACLE_ACCT_NUM_MV TO COGNOS_RO;

GRANT SELECT ON GKDW.GK_ORACLE_ACCT_NUM_MV TO DWHREAD;

