DROP MATERIALIZED VIEW GKDW.ENT_TRANS_BOOKINGS_MV;
CREATE MATERIALIZED VIEW GKDW.ENT_TRANS_BOOKINGS_MV 
TABLESPACE GDWSML
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 29/01/2021 12:19:12 (QP5 v5.115.810.9015) */
SELECT   * FROM ent_trans_bookings@slx;

COMMENT ON MATERIALIZED VIEW GKDW.ENT_TRANS_BOOKINGS_MV IS 'snapshot table for snapshot GKDW.ENT_TRANS_BOOKINGS_MV';

GRANT SELECT ON GKDW.ENT_TRANS_BOOKINGS_MV TO COGNOS_RO;

GRANT SELECT ON GKDW.ENT_TRANS_BOOKINGS_MV TO DWHREAD;

