DROP MATERIALIZED VIEW GKDW.GK_COURSE_CONF_LETTER_MV;
CREATE MATERIALIZED VIEW GKDW.GK_COURSE_CONF_LETTER_MV 
TABLESPACE GDWSML
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 29/01/2021 12:25:51 (QP5 v5.115.810.9015) */
SELECT   evxcourseid, gkn_autoemail_ltrgroupid FROM gkn_autoemail_grpcrs@slx;

COMMENT ON MATERIALIZED VIEW GKDW.GK_COURSE_CONF_LETTER_MV IS 'snapshot table for snapshot GKDW.GK_COURSE_CONF_LETTER_MV';

GRANT SELECT ON GKDW.GK_COURSE_CONF_LETTER_MV TO DWHREAD;

