DROP MATERIALIZED VIEW GKDW.LAB_COURSE_LOOKUP_MV;
CREATE MATERIALIZED VIEW GKDW.LAB_COURSE_LOOKUP_MV 
TABLESPACE GDWSML
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 29/01/2021 12:20:51 (QP5 v5.115.810.9015) */
SELECT   * FROM "lab_course_lookup_v"@rms_prod;

COMMENT ON MATERIALIZED VIEW GKDW.LAB_COURSE_LOOKUP_MV IS 'snapshot table for snapshot GKDW.LAB_COURSE_LOOKUP_MV';

GRANT SELECT ON GKDW.LAB_COURSE_LOOKUP_MV TO DWHREAD;

