DROP MATERIALIZED VIEW GKDW.IBM_COURSE_LOAD_MV;
CREATE MATERIALIZED VIEW GKDW.IBM_COURSE_LOAD_MV 
TABLESPACE GDWSML
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 29/01/2021 12:21:07 (QP5 v5.115.810.9015) */
SELECT   * FROM ibm_course_load;

COMMENT ON MATERIALIZED VIEW GKDW.IBM_COURSE_LOAD_MV IS 'snapshot table for snapshot GKDW.IBM_COURSE_LOAD_MV';

GRANT SELECT ON GKDW.IBM_COURSE_LOAD_MV TO DWHREAD;

