DROP MATERIALIZED VIEW GKDW.GK_CHANNEL_CONF_EMAIL_MV;
CREATE MATERIALIZED VIEW GKDW.GK_CHANNEL_CONF_EMAIL_MV 
TABLESPACE GDWSML
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 29/01/2021 12:26:09 (QP5 v5.115.810.9015) */
SELECT   *
  FROM   gk_channel_enroll_conf_v@slx
 WHERE   enrollstatus = 'Confirmed';

COMMENT ON MATERIALIZED VIEW GKDW.GK_CHANNEL_CONF_EMAIL_MV IS 'snapshot table for snapshot GKDW.GK_CHANNEL_CONF_EMAIL_MV';

GRANT SELECT ON GKDW.GK_CHANNEL_CONF_EMAIL_MV TO DWHREAD;

