DROP MATERIALIZED VIEW GKDW.GK_PROMO_FULFILL_MV;
CREATE MATERIALIZED VIEW GKDW.GK_PROMO_FULFILL_MV 
TABLESPACE GDWMED
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 29/01/2021 12:23:04 (QP5 v5.115.810.9015) */
SELECT   * FROM gk_promo_fulfill_v@gkhub;

COMMENT ON MATERIALIZED VIEW GKDW.GK_PROMO_FULFILL_MV IS 'snapshot table for snapshot GKDW.GK_PROMO_FULFILL_MV';

GRANT SELECT ON GKDW.GK_PROMO_FULFILL_MV TO DWHREAD;

