DROP PROCEDURE GKDW.GK_REMOTE_LABS_REFRESH_PROC;

CREATE OR REPLACE PROCEDURE GKDW.gk_remote_labs_refresh_proc as
begin
DBMS_SNAPSHOT.REFRESH('RMS_EVENT_POD_MV');
DBMS_SNAPSHOT.REFRESH('RMS_POD_LABS_MV');
end;
/


GRANT EXECUTE ON GKDW.GK_REMOTE_LABS_REFRESH_PROC TO COGNOS_RO;

GRANT EXECUTE ON GKDW.GK_REMOTE_LABS_REFRESH_PROC TO EXCEL_RO;

